services:
    mirotalk:
        image: mirotalk/p2p:latest
        container_name: mirotalk
        hostname: mirotalk
        restart: unless-stopped
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ./.env:/src/.env:ro
            # Rebranding:
            - ./app/src/config.js:/src/app/src/config.js:ro
            # Optional volumes for real-time updates:
            - ./app/:/src/app/:ro
            - ./public/:/src/public/:ro
# Uncomment below, remove "ports:" section above and configure labels as
# needed for LetsEncrypt TLS certificates with Traefik.
# See https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
  # expose:
  #   - 8086
#   labels:
#     - "traefik.enable=true"
#     - "traefik.http.routers.mirotalk.rule=Host(`mirotalk.example.com`)"
#     - "traefik.http.routers.mirotalk.entrypoints=websecure"
#     - "traefik.http.routers.mirotalk.tls.certresolver=myresolver"
#     - "traefik.http.services.mirotalk.loadbalancer.server.port=3000"
